export const jobsSeed = [
  {
    id: 'bao-ve-ca-dem',
    title: 'Nhan vien bao ve ca dem',
    location: 'Quan 1, TP. Ho Chi Minh',
    salary: '9.000.000 VND / thang',
    badge: 'NEW',
    company: 'QUOC HUNG PALACE',
    address: '50 123/6, Tho Xuan, Thanh Hoa, Viet Nam',
    description:
      'Chung toi dang tim kiem nhan vien bao ve chuyen nghiep va canh giac cao cho khu vuc duoc phan cong.',
    requirements: [
      'Tot nghiep THPT hoac tuong duong.',
      'Chieu cao toi thieu Nam 1m70, Nu 1m60.',
      'Suc khoe tot, ly lich tu phap trong sach.',
      'Ky nang giao tiep va giai quyet xung dot tot.',
      'Co xac nhan ky nang doi pho khan cap la mot loi the lon.',
      'Co kinh nghiem giam sat bao ve ben ngoai.',
    ],
    experience: '1-2 Nam',
    candidates: '24 Ung vien',
    summary: {
      place: 'Thanh Hoa',
      mode: 'Toan thoi gian',
      postedAt: '2 ngay truoc',
    },
    schedule: [
      { label: 'LUONG PHIEN', value: 'Lam theo ca' },
      { label: 'THOI GIAN', value: '8h hoac 12h' },
      { label: 'NGAY NGHI', value: '4 Ngay / Thang' },
      { label: 'HINH THUC', value: 'Toan thoi gian' },
    ],
  },
  {
    id: 'bao-ve-su-kien',
    title: 'Nhan vien bao ve su kien',
    location: 'Thanh Hoa',
    salary: '8.000.000 VND / thang',
    badge: 'NEW',
    company: 'QUOC HUNG PALACE',
    address: '50 123/6, Tho Xuan, Thanh Hoa, Viet Nam',
    description:
      'Dam bao ky luat va kiem soat ra vao tai cac su kien dong nguoi.',
    requirements: ['Tot nghiep THPT.', 'Ky nang giao tiep tot.'],
    experience: '1-2 Nam',
    candidates: '24 Ung vien',
    summary: { place: 'Thanh Hoa', mode: 'Toan thoi gian', postedAt: '2 ngay truoc' },
    schedule: [
      { label: 'LUONG PHIEN', value: 'Lam theo ca' },
      { label: 'THOI GIAN', value: '8h hoac 12h' },
      { label: 'NGAY NGHI', value: '4 Ngay / Thang' },
      { label: 'HINH THUC', value: 'Toan thoi gian' },
    ],
  },
  {
    id: 'bao-ve-that-thoat-ban-le',
    title: 'Nhan vien chong that thoat ban le',
    location: 'Ha Noi',
    salary: '8.400.000 VND / thang',
    badge: '',
    company: 'QUOC HUNG PALACE',
    address: '50 123/6, Tho Xuan, Thanh Hoa, Viet Nam',
    description: 'Giam sat khu ban hang va ngua that thoat tai san.',
    requirements: ['Can than, trung thuc.', 'Kinh nghiem quan sat camera la loi the.'],
    experience: '1-2 Nam',
    candidates: '24 Ung vien',
    summary: { place: 'Ha Noi', mode: 'Toan thoi gian', postedAt: '3 ngay truoc' },
    schedule: [
      { label: 'LUONG PHIEN', value: 'Lam theo ca' },
      { label: 'THOI GIAN', value: '8h hoac 12h' },
      { label: 'NGAY NGHI', value: '4 Ngay / Thang' },
      { label: 'HINH THUC', value: 'Toan thoi gian' },
    ],
  },
];
