ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS requirements JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS experience VARCHAR(128) NULL;

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS schedule_type VARCHAR(128) NULL;

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS work_hours VARCHAR(128) NULL;

ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS day_off VARCHAR(128) NULL;
